name: My First Workflow

on:
  workflow_dispatch:
    inputs:
      greeting_name:
        description: 'Who should be greeted?'
        default: 'World'

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: echo "Hello, ${{ github.event.inputs.greeting_name }}!"